### PR TITLE
Add support for cmake-gui building (if Qt available and specified)

### PR DESCRIPTION
**Pull request by aphecetche**
Done by adding the --qt-gui option to bootstrap if QTBINDIR is available.

### CODE REVIEW

**Comment by srivathsanmurali** [comment]
Hey thanks for PR, this looks good.
I am just looking into why the CI is failing. Once we have an answer for that, I will merge this :+1:

**Comment by aphecetche** [comment]
Is there anything I can do on my side to help ?
(but I note the CI is using MacOS 10.13, and I only have -easy, at least- access to 10.14 systems)

**Comment by srivathsanmurali** [comment]
I ran the master branch again on the CI. It seemed to have failed too. 
This seems to be an issue with the travis CI script itself.

**Comment by srivathsanmurali** [comment]
I think your changes look good. Lets merge your PR and tackle the CI script seperatly.

**Comment by srivathsanmurali** [comment]
Thanks for the PR.

**Pull request merged**
